# PR Insights Labeler - Advanced Configuration
#
# Advanced configuration with optional features for customization.
# Uncomment sections as needed for your use case.

name: PR Insights Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Read PR files
      pull-requests: write # Apply labels
      issues: write # Post comments

    steps:
      - uses: actions/checkout@v4

      - uses: jey3dayo/pr-insights-labeler@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # ============================================
          # Basic Configuration
          # ============================================

          # Size Limits
          file_size_limit: "100KB" # Maximum file size
          file_lines_limit: "500" # Maximum lines per file
          pr_additions_limit: "5000" # Maximum total additions
          pr_files_limit: "50" # Maximum changed files

          # Label Control (Enable/Disable label types)
          size_enabled: "true" # Enable size labels
          category_enabled: "true" # Enable category labels
          risk_enabled: "true" # Enable risk labels
          # complexity_enabled: "false" # Enable complexity labels (disabled by default)

          # GitHub Actions Summary & Comments
          enable_summary: "true" # Publish metrics to GitHub Actions Summary
          comment_on_pr: "auto" # Auto-detect when to comment (auto/always/never)


          # ============================================
          # Optional: Custom Thresholds
          # ============================================
          # Uncomment to customize size label thresholds
          # size_thresholds: '{"small": 100, "medium": 300, "large": 700, "xlarge": 2000}'

          # Uncomment to enable and customize complexity thresholds
          # complexity_enabled: "true"
          # complexity_thresholds: '{"medium": 15, "high": 30}'

          # ============================================
          # Optional: File Exclusion Patterns
          # ============================================
          # Exclude specific files/directories from analysis
          # Use glob patterns to match files. Multiple patterns can be combined.

          # Example 1: Ignore specific large files
          # Useful when you have known large files that should not trigger violations
          # additional_exclude_patterns: |
          #   docs/large-api-spec.json
          #   assets/generated-data.ts
          #   config/all-feature-flags.json

          # Example 2: Ignore generated/vendor code
          # Common for projects with code generation (Protobuf, GraphQL, OpenAPI)
          # additional_exclude_patterns: |
          #   **/*.generated.ts
          #   **/*.pb.go
          #   **/*.gen.go
          #   **/graphql/generated/**
          #   vendor/**
          #   third_party/**
          #   node_modules/**

          # Example 3: Ignore test fixtures and snapshots
          # Prevents test data files from affecting PR metrics
          # additional_exclude_patterns: |
          #   __snapshots__/**
          #   test/fixtures/**
          #   **/*.fixture.json
          #   **/*.mock.ts
          #   **/testdata/**

          # Uncomment to disable default excludes (not recommended)
          # By default, excludes node_modules, dist, build, lock files, etc.
          # use_default_excludes: "false"

          # ============================================
          # Optional: Workflow Quality Gates
          # ============================================
          # Fail workflow if violations are detected

          # Uncomment to fail if files exceed size/line limits
          # fail_on_large_files: "true"

          # Uncomment to fail if too many files changed
          # fail_on_too_many_files: "true"

          # Uncomment to fail if PR size exceeds threshold
          # Options: small, medium, large, xlarge, xxlarge
          # fail_on_pr_size: "xlarge"

          # ============================================
          # Optional: Label Customization
          # ============================================
          # Customize violation label names

          # large_files_label: "violations/large-files"
          # too_many_files_label: "violations/too-many-files"
          # too_many_lines_label: "violations/too-many-lines"
          # excessive_changes_label: "violations/excessive-changes"

          # Auto-remove labels when limits are no longer exceeded
          # auto_remove_labels: "true"

          # ============================================
          # Optional: Multi-language Support
          # ============================================
          # Set output language (en/ja)

          # language: "en"  # English (default)
          # language: "ja"  # Japanese

          # ============================================
          # Optional: Skip Draft PRs
          # ============================================
          # Skip labeling for draft PRs

          # skip_draft_pr: "true"  # Default: true
# ============================================
# Common Configuration Patterns
# ============================================
#
# Strict Mode (Mission-Critical Projects):
#   Uncomment fail_on_large_files, fail_on_too_many_files
#   Set fail_on_pr_size: "large"
#   Set comment_on_pr: "always"
#
# Monorepo with Multiple Teams:
#   Use .github/pr-labeler.yml to configure category labels
#   based on directory structure (e.g., packages/frontend, packages/backend)
#
# Open Source Projects:
#   Keep fail_on_* options disabled to avoid discouraging contributions
#   Consider using pull_request_target for fork PRs
#
# Generated Code Projects (Protobuf, GraphQL, OpenAPI):
#   additional_exclude_patterns: |
#     **/*.generated.ts
#     **/*.pb.go
#     **/*.gen.go
#     **/graphql/generated/**
#     **/openapi/generated/**
#   Use to prevent auto-generated files from triggering violations
#
# Projects with Large Test Fixtures:
#   additional_exclude_patterns: |
#     __snapshots__/**
#     test/fixtures/**
#     **/*.fixture.json
#     **/testdata/**
#   Exclude test data to focus metrics on production code
#
# ============================================
# Related Documentation
# ============================================
#
# Configuration Guide: https://github.com/jey3dayo/pr-insights-labeler/blob/main/docs/en/configuration.md
# Advanced Usage: https://github.com/jey3dayo/pr-insights-labeler/blob/main/docs/en/advanced-usage.md
