# PR Insights Labeler - Fork-Friendly Configuration
#
# Secure configuration for handling PRs from external forks.
# Uses pull_request_target event for proper permissions.

name: PR Check (Fork-Friendly)

on:
  pull_request_target: # Use pull_request_target for fork PRs
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Read PR files
      pull-requests: write # Apply labels
      issues: write # Post comments

    steps:
      # IMPORTANT: Check out the PR's code, not the base branch
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: jey3dayo/pr-insights-labeler@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Basic Configuration
          size_enabled: "true"
          category_enabled: "true"
          risk_enabled: "true"

          # Enable Summary and Comments
          enable_summary: "true"
          comment_on_pr: "auto"
# Security Considerations:
#
# ⚠️ IMPORTANT: pull_request_target runs in the context of the base repository
#    and has access to secrets. Only use this event when necessary.
#
# - Risk: Malicious code in fork PRs could access secrets
# - Mitigation: This action only reads files and applies labels; does not execute code
# - Best Practice: Review fork PRs before approving workflows
#
# When to Use:
#
# ✅ Open source projects accepting external contributions
# ✅ Public repositories with fork PRs
# ❌ Private repositories (use pull_request event instead)
#
# Alternative: Summary-Only Mode (No Write Permissions)
#
# If you want to avoid granting write permissions to fork PRs,
# see examples/workflows/summary-only.yml
