# PR Insights Labeler - Strict Mode Configuration
#
# Enforces code quality standards by failing the workflow when violations are detected.
# Recommended for mission-critical codebases.

name: PR Check (Strict)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v4

      - uses: jey3dayo/pr-insights-labeler@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Strict Size Limits
          file_size_limit: "100KB" # Maximum file size
          file_lines_limit: "300" # Stricter line limit
          pr_additions_limit: "500" # Stricter PR addition limit
          pr_files_limit: "30" # Stricter file count limit

          # Enable All Label Types
          size_enabled: "true"
          category_enabled: "true"
          risk_enabled: "true"
          complexity_enabled: "true" # Enable complexity checks

          # Strict Complexity Thresholds
          complexity_thresholds: '{"medium": 10, "high": 20}'

          # Quality Gates (Fail on Violations)
          fail_on_large_files: "true" # Fail if files exceed size/line limits
          fail_on_too_many_files: "true" # Fail if too many files changed
          fail_on_pr_size: "large" # Fail if PR size >= "large"

          # Always Comment on Violations
          comment_on_pr: "always"

          # Enable Summary
          enable_summary: "true"

          # Custom Violation Labels
          large_files_label: "violations/large-files"
          too_many_files_label: "violations/too-many-files"
          too_many_lines_label: "violations/too-many-lines"
          excessive_changes_label: "violations/excessive-changes"
# Use Cases:
#
# ✅ Mission-critical codebases requiring review for large changes
# ✅ Enforcing code style and complexity standards
# ✅ Preventing accidental commits of large files
# ❌ Open source projects (may discourage contributions)
#
# Tips:
#
# 1. Adjust limits based on your team's standards
# 2. Consider using fail_on_pr_size: "xlarge" instead of "large" for less strict enforcement
# 3. Disable complexity_enabled if ESLint complexity checks are too strict
# 4. Use fail_on_large_files: "false" to only warn without failing
